services:
  ketchupbot-discord:
    image: ghcr.io/galaxypedia-wiki/ketchupbot-discord:main
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    build:
      context: .
      dockerfile: ketchupbot-discord/Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]